/**
 * Mobieve Auth
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * OpenAPI spec version: 2019-12-11T20:25:45Z
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */


import ApiClient from '../ApiClient';





/**
* The ArrayOfObjects model module.
* @module Model/ArrayOfObjects
* @version 0.1.0
*/
export default class ArrayOfObjects {
    /**
    * Constructs a new <code>ArrayOfObjects</code>.
    * @alias module:Model/ArrayOfObjects
    * @class
    * @param data {Object} 
    * @param currentPage {Number} 
    * @param firstPageUrl {String} 
    * @param from {Number} 
    * @param lastPage {Number} 
    * @param lastPageUrl {String} 
    * @param path {String} 
    * @param perPage {Number} 
    * @param to {Number} 
    * @param total {Number} 
    */

    constructor(data, currentPage, firstPageUrl, from, lastPage, lastPageUrl, path, perPage, to, total) {
        

        
        

        this['data'] = data;this['current_page'] = currentPage;this['first_page_url'] = firstPageUrl;this['from'] = from;this['last_page'] = lastPage;this['last_page_url'] = lastPageUrl;this['path'] = path;this['per_page'] = perPage;this['to'] = to;this['total'] = total;

        
    }

    /**
    * Constructs a <code>ArrayOfObjects</code> from a plain JavaScript object, optionally creating a new instance.
    * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
    * @param {Object} data The plain JavaScript object bearing properties of interest.
    * @param {module:Model/ArrayOfObjects} obj Optional instance to populate.
    * @return {module:Model/ArrayOfObjects} The populated <code>ArrayOfObjects</code> instance.
    */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new ArrayOfObjects();

            
            
            

            if (data.hasOwnProperty('data')) {
                obj['data'] = ApiClient.convertToType(data['data'], Object);
            }
            if (data.hasOwnProperty('current_page')) {
                obj['current_page'] = ApiClient.convertToType(data['current_page'], 'Number');
            }
            if (data.hasOwnProperty('first_page_url')) {
                obj['first_page_url'] = ApiClient.convertToType(data['first_page_url'], 'String');
            }
            if (data.hasOwnProperty('from')) {
                obj['from'] = ApiClient.convertToType(data['from'], 'Number');
            }
            if (data.hasOwnProperty('last_page')) {
                obj['last_page'] = ApiClient.convertToType(data['last_page'], 'Number');
            }
            if (data.hasOwnProperty('last_page_url')) {
                obj['last_page_url'] = ApiClient.convertToType(data['last_page_url'], 'String');
            }
            if (data.hasOwnProperty('path')) {
                obj['path'] = ApiClient.convertToType(data['path'], 'String');
            }
            if (data.hasOwnProperty('per_page')) {
                obj['per_page'] = ApiClient.convertToType(data['per_page'], 'Number');
            }
            if (data.hasOwnProperty('to')) {
                obj['to'] = ApiClient.convertToType(data['to'], 'Number');
            }
            if (data.hasOwnProperty('total')) {
                obj['total'] = ApiClient.convertToType(data['total'], 'Number');
            }
        }
        return obj;
    }

    /**
    * @member {Object} data
    */
    data = undefined;
    /**
    * @member {Number} current_page
    */
    current_page = undefined;
    /**
    * @member {String} first_page_url
    */
    first_page_url = undefined;
    /**
    * @member {Number} from
    */
    from = undefined;
    /**
    * @member {Number} last_page
    */
    last_page = undefined;
    /**
    * @member {String} last_page_url
    */
    last_page_url = undefined;
    /**
    * @member {String} path
    */
    path = undefined;
    /**
    * @member {Number} per_page
    */
    per_page = undefined;
    /**
    * @member {Number} to
    */
    to = undefined;
    /**
    * @member {Number} total
    */
    total = undefined;








}


