/**
 * Mobieve Auth
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * OpenAPI spec version: 2019-12-11T20:25:45Z
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */


import ApiClient from '../ApiClient';





/**
* The Client model module.
* @module Model/Client
* @version 0.1.0
*/
export default class Client {
    /**
    * Constructs a new <code>Client</code>.
    * @alias module:Model/Client
    * @class
    * @param id {Number} 
    * @param userId {Number} 
    * @param name {String} 
    * @param secret {String} 
    * @param redirect {String} 
    * @param personalAccessClient {Boolean} 
    * @param passwordClient {Boolean} 
    * @param revoked {Boolean} 
    * @param createdAt {String} 
    * @param updatedAt {String} 
    */

    constructor(id, userId, name, secret, redirect, personalAccessClient, passwordClient, revoked, createdAt, updatedAt) {
        

        
        

        this['id'] = id;this['user_id'] = userId;this['name'] = name;this['secret'] = secret;this['redirect'] = redirect;this['personal_access_client'] = personalAccessClient;this['password_client'] = passwordClient;this['revoked'] = revoked;this['created_at'] = createdAt;this['updated_at'] = updatedAt;

        
    }

    /**
    * Constructs a <code>Client</code> from a plain JavaScript object, optionally creating a new instance.
    * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
    * @param {Object} data The plain JavaScript object bearing properties of interest.
    * @param {module:Model/Client} obj Optional instance to populate.
    * @return {module:Model/Client} The populated <code>Client</code> instance.
    */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new Client();

            
            
            

            if (data.hasOwnProperty('id')) {
                obj['id'] = ApiClient.convertToType(data['id'], 'Number');
            }
            if (data.hasOwnProperty('user_id')) {
                obj['user_id'] = ApiClient.convertToType(data['user_id'], 'Number');
            }
            if (data.hasOwnProperty('name')) {
                obj['name'] = ApiClient.convertToType(data['name'], 'String');
            }
            if (data.hasOwnProperty('secret')) {
                obj['secret'] = ApiClient.convertToType(data['secret'], 'String');
            }
            if (data.hasOwnProperty('redirect')) {
                obj['redirect'] = ApiClient.convertToType(data['redirect'], 'String');
            }
            if (data.hasOwnProperty('personal_access_client')) {
                obj['personal_access_client'] = ApiClient.convertToType(data['personal_access_client'], 'Boolean');
            }
            if (data.hasOwnProperty('password_client')) {
                obj['password_client'] = ApiClient.convertToType(data['password_client'], 'Boolean');
            }
            if (data.hasOwnProperty('revoked')) {
                obj['revoked'] = ApiClient.convertToType(data['revoked'], 'Boolean');
            }
            if (data.hasOwnProperty('created_at')) {
                obj['created_at'] = ApiClient.convertToType(data['created_at'], 'String');
            }
            if (data.hasOwnProperty('updated_at')) {
                obj['updated_at'] = ApiClient.convertToType(data['updated_at'], 'String');
            }
        }
        return obj;
    }

    /**
    * @member {Number} id
    */
    id = undefined;
    /**
    * @member {Number} user_id
    */
    user_id = undefined;
    /**
    * @member {String} name
    */
    name = undefined;
    /**
    * @member {String} secret
    */
    secret = undefined;
    /**
    * @member {String} redirect
    */
    redirect = undefined;
    /**
    * @member {Boolean} personal_access_client
    */
    personal_access_client = undefined;
    /**
    * @member {Boolean} password_client
    */
    password_client = undefined;
    /**
    * @member {Boolean} revoked
    */
    revoked = undefined;
    /**
    * @member {String} created_at
    */
    created_at = undefined;
    /**
    * @member {String} updated_at
    */
    updated_at = undefined;








}


