/**
 * Mobieve Auth
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * OpenAPI spec version: 2019-12-11T20:25:45Z
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */


import ApiClient from '../ApiClient';





/**
* The Empty model module.
* @module Model/Empty
* @version 0.1.0
*/
export default class Empty {
    /**
    * Constructs a new <code>Empty</code>.
    * @alias module:Model/Empty
    * @class
    */

    constructor() {
        

        
        

        

        
    }

    /**
    * Constructs a <code>Empty</code> from a plain JavaScript object, optionally creating a new instance.
    * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
    * @param {Object} data The plain JavaScript object bearing properties of interest.
    * @param {module:Model/Empty} obj Optional instance to populate.
    * @return {module:Model/Empty} The populated <code>Empty</code> instance.
    */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new Empty();

            
            
            

        }
        return obj;
    }









}


