/**
 * Mobieve Auth
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * OpenAPI spec version: 2019-12-11T20:25:45Z
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */


import ApiClient from '../ApiClient';





/**
* The Permission model module.
* @module Model/Permission
* @version 0.1.0
*/
export default class Permission {
    /**
    * Constructs a new <code>Permission</code>.
    * @alias module:Model/Permission
    * @class
    * @param name {String} 
    */

    constructor(name) {
        

        
        

        this['name'] = name;

        
    }

    /**
    * Constructs a <code>Permission</code> from a plain JavaScript object, optionally creating a new instance.
    * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
    * @param {Object} data The plain JavaScript object bearing properties of interest.
    * @param {module:Model/Permission} obj Optional instance to populate.
    * @return {module:Model/Permission} The populated <code>Permission</code> instance.
    */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new Permission();

            
            
            

            if (data.hasOwnProperty('id')) {
                obj['id'] = ApiClient.convertToType(data['id'], 'Number');
            }
            if (data.hasOwnProperty('name')) {
                obj['name'] = ApiClient.convertToType(data['name'], 'String');
            }
            if (data.hasOwnProperty('title')) {
                obj['title'] = ApiClient.convertToType(data['title'], 'String');
            }
            if (data.hasOwnProperty('api_id')) {
                obj['api_id'] = ApiClient.convertToType(data['api_id'], 'Number');
            }
            if (data.hasOwnProperty('api_name')) {
                obj['api_name'] = ApiClient.convertToType(data['api_name'], 'String');
            }
            if (data.hasOwnProperty('resource_name')) {
                obj['resource_name'] = ApiClient.convertToType(data['resource_name'], 'String');
            }
        }
        return obj;
    }

    /**
    * @member {Number} id
    */
    id = undefined;
    /**
    * @member {String} name
    */
    name = undefined;
    /**
    * @member {String} title
    */
    title = undefined;
    /**
    * @member {Number} api_id
    */
    api_id = undefined;
    /**
    * @member {String} api_name
    */
    api_name = undefined;
    /**
    * @member {String} resource_name
    */
    resource_name = undefined;








}


