/**
 * Mobieve Auth
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * OpenAPI spec version: 2019-12-11T20:25:45Z
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */


import ApiClient from '../ApiClient';





/**
* The Role model module.
* @module Model/Role
* @version 0.1.0
*/
export default class Role {
    /**
    * Constructs a new <code>Role</code>.
    * @alias module:Model/Role
    * @class
    * @param id {Number} 
    * @param name {String} 
    * @param title {String} 
    * @param createdAt {String} 
    * @param updatedAt {String} 
    */

    constructor(id, name, title, createdAt, updatedAt) {
        

        
        

        this['id'] = id;this['name'] = name;this['title'] = title;this['created_at'] = createdAt;this['updated_at'] = updatedAt;

        
    }

    /**
    * Constructs a <code>Role</code> from a plain JavaScript object, optionally creating a new instance.
    * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
    * @param {Object} data The plain JavaScript object bearing properties of interest.
    * @param {module:Model/Role} obj Optional instance to populate.
    * @return {module:Model/Role} The populated <code>Role</code> instance.
    */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new Role();

            
            
            

            if (data.hasOwnProperty('id')) {
                obj['id'] = ApiClient.convertToType(data['id'], 'Number');
            }
            if (data.hasOwnProperty('name')) {
                obj['name'] = ApiClient.convertToType(data['name'], 'String');
            }
            if (data.hasOwnProperty('title')) {
                obj['title'] = ApiClient.convertToType(data['title'], 'String');
            }
            if (data.hasOwnProperty('created_at')) {
                obj['created_at'] = ApiClient.convertToType(data['created_at'], 'String');
            }
            if (data.hasOwnProperty('updated_at')) {
                obj['updated_at'] = ApiClient.convertToType(data['updated_at'], 'String');
            }
            if (data.hasOwnProperty('permissions')) {
                obj['permissions'] = ApiClient.convertToType(data['permissions'], Object);
            }
            if (data.hasOwnProperty('users')) {
                obj['users'] = ApiClient.convertToType(data['users'], Object);
            }
        }
        return obj;
    }

    /**
    * @member {Number} id
    */
    id = undefined;
    /**
    * @member {String} name
    */
    name = undefined;
    /**
    * @member {String} title
    */
    title = undefined;
    /**
    * @member {String} created_at
    */
    created_at = undefined;
    /**
    * @member {String} updated_at
    */
    updated_at = undefined;
    /**
    * @member {Object} permissions
    */
    permissions = undefined;
    /**
    * @member {Object} users
    */
    users = undefined;








}


