/**
 * Mobieve Auth
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * OpenAPI spec version: 2019-12-11T20:25:45Z
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */


import ApiClient from '../ApiClient';





/**
* The RoleUser model module.
* @module Model/RoleUser
* @version 0.1.0
*/
export default class RoleUser {
    /**
    * Constructs a new <code>RoleUser</code>.
    * @alias module:Model/RoleUser
    * @class
    * @param id {Number} 
    * @param userId {Number} 
    * @param roleId {Number} 
    */

    constructor(id, userId, roleId) {
        

        
        

        this['id'] = id;this['user_id'] = userId;this['role_id'] = roleId;

        
    }

    /**
    * Constructs a <code>RoleUser</code> from a plain JavaScript object, optionally creating a new instance.
    * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
    * @param {Object} data The plain JavaScript object bearing properties of interest.
    * @param {module:Model/RoleUser} obj Optional instance to populate.
    * @return {module:Model/RoleUser} The populated <code>RoleUser</code> instance.
    */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new RoleUser();

            
            
            

            if (data.hasOwnProperty('id')) {
                obj['id'] = ApiClient.convertToType(data['id'], 'Number');
            }
            if (data.hasOwnProperty('user_id')) {
                obj['user_id'] = ApiClient.convertToType(data['user_id'], 'Number');
            }
            if (data.hasOwnProperty('role_id')) {
                obj['role_id'] = ApiClient.convertToType(data['role_id'], 'Number');
            }
        }
        return obj;
    }

    /**
    * @member {Number} id
    */
    id = undefined;
    /**
    * @member {Number} user_id
    */
    user_id = undefined;
    /**
    * @member {Number} role_id
    */
    role_id = undefined;








}


