/**
 * Mobieve Auth
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * OpenAPI spec version: 2019-12-11T20:25:45Z
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */


import ApiClient from '../ApiClient';





/**
* The TeamUser model module.
* @module Model/TeamUser
* @version 0.1.0
*/
export default class TeamUser {
    /**
    * Constructs a new <code>TeamUser</code>.
    * @alias module:Model/TeamUser
    * @class
    * @param id {Number} 
    * @param userId {Number} 
    * @param teamId {Number} 
    */

    constructor(id, userId, teamId) {
        

        
        

        this['id'] = id;this['user_id'] = userId;this['team_id'] = teamId;

        
    }

    /**
    * Constructs a <code>TeamUser</code> from a plain JavaScript object, optionally creating a new instance.
    * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
    * @param {Object} data The plain JavaScript object bearing properties of interest.
    * @param {module:Model/TeamUser} obj Optional instance to populate.
    * @return {module:Model/TeamUser} The populated <code>TeamUser</code> instance.
    */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new TeamUser();

            
            
            

            if (data.hasOwnProperty('id')) {
                obj['id'] = ApiClient.convertToType(data['id'], 'Number');
            }
            if (data.hasOwnProperty('user_id')) {
                obj['user_id'] = ApiClient.convertToType(data['user_id'], 'Number');
            }
            if (data.hasOwnProperty('team_id')) {
                obj['team_id'] = ApiClient.convertToType(data['team_id'], 'Number');
            }
        }
        return obj;
    }

    /**
    * @member {Number} id
    */
    id = undefined;
    /**
    * @member {Number} user_id
    */
    user_id = undefined;
    /**
    * @member {Number} team_id
    */
    team_id = undefined;








}


